#!/bin/bash -x
#===============================================================================
#
#          FILE: deploy.sh
#
#         USAGE: ./deploy.sh
#
#   DESCRIPTION:  deployer
#
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Fernando Augusto Medeiros Silva (), fams@linuxplace.com.br
#  ORGANIZATION: Linuxplace
#       CREATED: 28/04/2020 21:56
#      REVISION:  ---
#===============================================================================

set -o nounset                              # Treat unset variables as an error

TMP_CHART=./curr_chart

function init(){
  # atribui a chave para conseguir clonar repos
  mkdir ~/.ssh
  ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
  echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa
}

function fetchChart(){
  # clona o helm chart template
  CHART_REPO=$1
  git clone $CHART_REPO ${TMP_CHART}
}

function helmdeploy(){
  image_name=$1
  deploy_name=$2
  namespace=$3
  echo Show Deploy
  pwd
  ls
  helm install --set image=${image_name}  -f values.yaml $deploy_name ${TMP_CHART} --namespace ${namespace}
}

function dispHelp(){
cat <<EOF
$0 command [params]

commands:
  init
  fetchchart -c <charturi>
  deploy -i <imagename> -n <namespace> -r <deployname>

 -h help
EOF

}
echo ${*}
#### comandos
if [ $# -lt 1 ] ; then
  dispHelp
  exit 1
fi


VERB=$1
shift
while getopts i:n:c:k:b:r:h OPCAO; do
     case "${OPCAO}" in
        i) IMAGENAME="${OPTARG}" ;;
        r) RELEASE_NAME="${OPTARG}" ;;
        c) CHART_REPO="${OPTARG}" ;;
        n) NAMESPACE="${OPTARG}" ;;
        h) dispHelp; exit ;;
     esac
done

# Debug
echo Show Runner
pwd
ls

case "$VERB" in
  init)
  init
  ;;
  fetchchart)
  fetchChart $CHART_REPO
  ;;
  deploy)
  helmdeploy ${IMAGENAME} ${RELEASE_NAME} ${NAMESPACE}
  ;;
  *)
  echo "Comando invalido $VERB"
  exit 1
  ;;
esac
